### ISSUE TITLE
[BUG] Hide left sidebar setting doesn't work properly

### ISSUE THREAD

**Issue by vanowm** [AnthoPakPak/StackOverflowPowerUser#3]
The left sidebar is hidden regardless if the setting is enabled or disabled on this page:
https://stackoverflow.com/questions/tagged/javascript

It hides/shows it properly on a question page.

It seems the extension hides the bar by default and showing it if option is disabled. IMO that's backwards from how it should've worked...

**Comment by AnthoPakPak** [comment]
You're right. To prevent the site content from jumping when js has loaded and executed, I added the hiding as a CSS rule, and disable the rule later if the user hasn't enabled the option. But since I run the js only on questions pages, it doesn't cancel the CSS rule on other pages.

Anyway, that might be a feature I'll remove in the future since SO now have this as a stock setting in user preferences:
![image](https://user-images.githubusercontent.com/16854916/116457325-8dd97700-a863-11eb-8c9f-bf4ee9a8f79f.png)

Funnily enough, while taking this screenshot for you I'm noticing that they also have added Keyboard Shortcuts! (but with weird keys choice)

**Comment by AnthoPakPak** [comment]
This feature has been removed from version 0.3.5, please switch to stock SO setting instead.
